# -*- coding: utf-8 -*-
"""DICTIONARIES

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HOnvA_EQNNQtbUTIkpMaF5-KRsDwdAZ2
"""

def squar():
  print('hello world')
squar()

dict={'name':'venkates','age':22}
print(dict['name'])
print(dict['age'])

dict={'name':{1:[1,2,3,4]}}
dict['name'][1][0]

"""NESTED DICT"""

dict={'venkates':{'prabhas':['mirchi','saaaho','rebel']}}   #venkatesh is key value of dict
dict['venkates']['prabhas'][-1][0] #prabhas is inside key value of venkatesh using indexing -1 is indexing of prabhas indexing 0 is is position of -1 is rebel 0 position is r"

