# -*- coding: utf-8 -*-
"""FIBONACCI SERIES

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzyX5Gu9XHfA_mRZsesKLen0RT_2IGJ5
"""



"""# **FIBONACCI**"""

n=int(input("enter the number"))
n1=0
n2=1
count=2
if n < 0:
  print("enter only +ve values")
elif n==1:
  print(n1)
else:
  print(n1)
  print(n2)
  while count<n:
    n3=n1+n2
    print(n3)
    count+=1
    n1=n2
    n2=n3

n=int(input("enter the number"))
n1=0
n2=1
count=2
if n<0:
  print("enter only +ve values")
elif n==1:
  print(n1)
else:
  print(n1)
  print(n2)
  while count<n:
    n3=n1+n2
    print(n3)
    count+=1
    n1=n2
    n2=n3